[project]
name = "mcp-using-fastmcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.2",
    "fastapi-mcp>=0.4.0",
    "fastmcp>=2.13.1",
    "feedparser>=6.0.12",
    "requests>=2.32.5",
    "uvicorn[standard]>=0.38.0",
]
